server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql:///passkey_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-not-delete-value: false
      logic-delete-value: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

passkey:
  id: "passkey.ciallo.io"
  name: "PassKeyDemo"
  origins:
    - "http://localhost:8080"
    - "http://localhost:8193"

